from starlette.middleware.base import BaseHTTPMiddleware
from fastapi import Request
from src.security.jwt import verify_access_token
from fastapi.responses import JSONResponse



# Routes that do not require authentication we write them in an array 
PUBLIC_ROUTES = ["/auth/login", "/auth/signup", "/docs", "/openapi.json"]

# Starlette auto executes the dispatch() method before executing the controllers 
class AuthMiddleware(BaseHTTPMiddleware):

    # async used because in this dispatch function , call_next() might call a route that has some complex processing
    # like quering a database , call another api , load files etc. async allows says , I might take time as im slow , so i
    # can pause for a while so other functions can be executed , basically provides threading
    async def dispatch(self, request: Request, call_next):

        # Allow public routes without verifying the jwt token 
        if request.url.path in PUBLIC_ROUTES:
            # when done checking simply pass the requests to the controllers using call_next()
            # call_next(request) returns the response generated by the next part of the application
            return await call_next(request)

        # if the route is private then read token from cookie
        token = request.cookies.get("access_token")

        if token is None:
            return JSONResponse(
                status_code=401,
                content={"detail": "Login Required"}
            )

        payload = verify_access_token(token)

        if payload is None:
            return JSONResponse(
                status_code=401,
                content={"detail": "Invalid or Expired Token"}
            )

        return await call_next(request)
